import type { Metadata } from 'next';
// import { Work_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import 'easymde/dist/easymde.min.css';
import { SanityLive } from '@/sanity/lib/live';

const workSans = localFont({
  src: [
    {
      path: '../public/fonts/WorkSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/WorkSans-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/WorkSans-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/WorkSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/WorkSans-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/fonts/WorkSans-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-work-sans',
});

export const metadata: Metadata = {
  title: 'Next blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${workSans.variable}`}>
        <SanityLive />
        {children}
      </body>
    </html>
  );
}
